Ac 31
ThomassenMichiel/Acara pull request #35
Opened 2020-04-26 14:48 UTC by RubenNeven

AC-31: User kan ticket kopen en dit wordt toegevoegd aan subscribed events van de user

2020-04-26 22:48 UTC, ThomassenCathleia requested changes
This already looks pretty nice. Be careful with copying code.

Some 'errors' could be avoided, some are good from learning from.

2020-04-26 22:48 UTC, ThomassenMichiel commented on src/main/java/be/acara/events/controller/OrderController.java
> +//    }
Try to remove all commented code when doing a PR.

2020-04-26 22:48 UTC, ThomassenMichiel commented on src/main/java/be/acara/events/controller/OrderController.java
> +//    }
Try to remove all commented code when doing a PR.

2020-04-26 22:48 UTC, ThomassenMichiel commented on src/main/java/be/acara/events/domain/User.java
> +//    private List<Order> orderList;
Try to remove all commented code when doing a PR.

2020-04-26 22:48 UTC, ThomassenMichiel commented on src/main/java/be/acara/events/security/WebSecurity.java
> +                .antMatchers(HttpMethod.POST, "/api/orders/**").hasAnyRole("ADMIN", "USER")
.authenticated() would be more approriate for this

2020-04-26 22:48 UTC, ThomassenMichiel commented on src/main/java/be/acara/events/service/EventServiceImpl.java
> +        eventRepository.save(event);
the .save(event) can be removed. This method could actually be moved to the Event domain class.

2020-04-26 22:48 UTC, ThomassenMichiel commented on src/main/java/be/acara/events/service/OrderServiceImpl.java
> +                .orElseThrow(() -> new EventNotFoundException(String.format("Order with ID %d not found", id)));
new OrderNotFoundException instead of EventNotFoundException

2020-04-26 22:48 UTC, ThomassenMichiel commented on src/main/java/be/acara/events/service/OrderServiceImpl.java
> +        return order;
move eventService.addAttendee(event, user) above Order order = orderRepsoitory.... and return the order directly. (return orderRepository....)

Keep in mind the other comment regarding eventService.addAttendee

2020-04-26 22:48 UTC, ThomassenMichiel commented on src/main/java/be/acara/events/service/OrderServiceImpl.java
> +            throw new EventNotFoundException(String.format("Order with ID %d not found", id));
throw new OrderNotFoundException....

2020-04-26 22:48 UTC, ThomassenMichiel commented on src/main/java/be/acara/events/service/mapper/OrderMapper.java
> +//        List<CreateOrderDto> collect = page.getContent().stream().collect(Collectors.toList());
Remove commented out code

2020-04-26 22:49 UTC, ThomassenMichiel commented on src/main/java/be/acara/events/domain/User.java
> +//    private List<Order> orderList;
This one causes the merge conflict.

2020-04-27 16:54 UTC, ThomassenCathleia requested changes

2020-04-27 16:54 UTC, ThomassenMichiel commented on src/test/java/be/acara/events/service/OrderServiceUnitTest.java
> +//}
Do not include commented out code in your commits.

2020-04-27 18:24 UTC, TomHaeldermans94 approved these changes

2020-04-28 20:10 UTC, ThomassenCathleia approved these changes

2020-04-28 20:11 UTC, merged

2020-05-04 13:32 UTC, sbottelbergs commented on src/main/java/be/acara/events/controller/dto/CreateOrderDto.java
> +@NoArgsConstructor
Not sure if no-args constructor is necessary

2020-05-04 13:32 UTC, sbottelbergs commented on src/main/java/be/acara/events/controller/dto/OrderDto.java
> +    Event event;
Event domain class in DTO?

2020-05-04 13:32 UTC, sbottelbergs commented on src/main/java/be/acara/events/controller/dto/OrderDto.java
> +    User user;
User domain class in DTO?